# Generated by Django 2.2.2 on 2019-06-08 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='pub_date',
        ),
    ]
