# Generated by Django 2.2.2 on 2019-06-08 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_books_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksinformation',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Books'),
        ),
    ]
