# Generated by Django 2.2.2 on 2019-06-08 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20190608_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booksinformation',
            name='book',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='books.Books'),
        ),
    ]
